#!/usr/bin/env python3
"""Collect HyDE leaderboard rows into paper-table-ready files."""

from __future__ import annotations

import argparse
import csv
import json
import re
from pathlib import Path
from typing import Any, Iterable

SCRIPT_DIR = Path(__file__).resolve().parent
METRICS = (
    "gold_recall",
    "gold_mrr",
    "gold_ndcg",
    "silver_loose_recall",
    "silver_loose_mrr",
    "silver_loose_ndcg",
    "union_loose_recall",
    "union_loose_mrr",
    "union_loose_ndcg",
    "gold_hit",
    "silver_strict_hit",
    "strict_union_hit",
)


def _read_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    if not isinstance(payload, dict):
        raise ValueError(f"Expected JSON object: {path}")
    return payload


def _top_k(path: Path) -> int:
    for part in path.parts:
        match = re.fullmatch(r"top_(\d+)", part)
        if match:
            return int(match.group(1))
    raise ValueError(f"Could not infer top-k from {path}")


def collect_rows(input_root: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for path in sorted(input_root.rglob("leaderboard_row.json")):
        payload = _read_json(path)
        if str(payload.get("method_name")) != "hyde":
            continue
        top_k = _top_k(path)
        row: dict[str, Any] = {
            "dataset": str(payload.get("dataset_name", "")),
            "method_name": "hyde",
            "top_k": top_k,
            "split": str(payload.get("split", "")),
            "run_name": str(payload.get("run_name", path.parent.name)),
            "n_queries": payload.get("n_queries"),
            "average_chunk_tokens": payload.get("average_chunk_tokens"),
            "source_path": str(path.relative_to(input_root)),
        }
        for metric in METRICS:
            row[f"{metric}@{top_k}"] = payload.get(f"{metric}@{top_k}")
        rows.append(row)
    return sorted(rows, key=lambda row: (str(row["dataset"]), int(row["top_k"]), str(row["run_name"])))


def _format(value: Any) -> str:
    return "--" if value is None else f"{float(value) * 100.0:.1f}"


def _write_jsonl(path: Path, rows: Iterable[dict[str, Any]]) -> None:
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False, sort_keys=True) + "\n")


def _write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    fieldnames = list(dict.fromkeys(key for row in rows for key in row))
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def _write_markdown(path: Path, rows: list[dict[str, Any]]) -> None:
    headers = ["Dataset", "Method", "TopK", "N", "Gold R", "Gold MRR", "Gold nDCG", "Union-L R", "Union-L MRR", "Union-L nDCG", "Union-S HR"]
    lines = ["| " + " | ".join(headers) + " |", "| " + " | ".join(["---"] * len(headers)) + " |"]
    for row in rows:
        k = int(row["top_k"])
        lines.append(
            "| "
            + " | ".join(
                [
                    str(row["dataset"]),
                    str(row["method_name"]),
                    str(k),
                    str(row.get("n_queries", "")),
                    _format(row.get(f"gold_recall@{k}")),
                    _format(row.get(f"gold_mrr@{k}")),
                    _format(row.get(f"gold_ndcg@{k}")),
                    _format(row.get(f"union_loose_recall@{k}")),
                    _format(row.get(f"union_loose_mrr@{k}")),
                    _format(row.get(f"union_loose_ndcg@{k}")),
                    _format(row.get(f"strict_union_hit@{k}")),
                ]
            )
            + " |"
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _latex_escape(text: str) -> str:
    replacements = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_", "{": r"\{", "}": r"\}"}
    return "".join(replacements.get(char, char) for char in text)


def _write_latex(path: Path, rows: list[dict[str, Any]]) -> None:
    lines = [
        "% Auto-generated by generate_hyde_retriever_table.py; values are percentages.",
        r"\begin{tabular}{llrrrrrr}",
        r"\toprule",
        r"Dataset & Method & TopK & N & Gold R & Gold MRR & Union-L R & Union-S HR \\",
        r"\midrule",
    ]
    for row in rows:
        k = int(row["top_k"])
        cells = [
            _latex_escape(str(row["dataset"])),
            _latex_escape(str(row["method_name"])),
            str(k),
            str(row.get("n_queries", "")),
            _format(row.get(f"gold_recall@{k}")),
            _format(row.get(f"gold_mrr@{k}")),
            _format(row.get(f"union_loose_recall@{k}")),
            _format(row.get(f"strict_union_hit@{k}")),
        ]
        lines.append(" & ".join(cells) + r" \\")
    lines.extend([r"\bottomrule", r"\end{tabular}", ""])
    path.write_text("\n".join(lines), encoding="utf-8")


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-root", type=Path, default=SCRIPT_DIR / "hyde_evaluations")
    parser.add_argument("--output-dir", type=Path, default=SCRIPT_DIR / "hyde_evaluations_Tables")
    parser.add_argument("--prefix", default="hyde_retriever_rows")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    input_root = args.input_root.expanduser().resolve()
    rows = collect_rows(input_root)
    if not rows:
        raise FileNotFoundError(f"No HyDE leaderboard rows found under {input_root}")
    output_dir = args.output_dir.expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    outputs = {
        "jsonl": output_dir / f"{args.prefix}.jsonl",
        "csv": output_dir / f"{args.prefix}.csv",
        "markdown": output_dir / f"{args.prefix}.md",
        "latex": output_dir / f"{args.prefix}.tex",
    }
    _write_jsonl(outputs["jsonl"], rows)
    _write_csv(outputs["csv"], rows)
    _write_markdown(outputs["markdown"], rows)
    _write_latex(outputs["latex"], rows)
    print(json.dumps({"rows": len(rows), "outputs": {key: str(value) for key, value in outputs.items()}}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
